Test workflow

diff --git a/.github/workflows/otc-golangci-lint.yaml b/.github/workflows/otc-golangci-lint.yaml
--- a/.github/workflows/otc-golangci-lint.yaml
+++ b/.github/workflows/otc-golangci-lint.yaml
@@ -36,7 +36,7 @@ jobs:
           git clone https://github.com/teamssix/container-escape-check.git
           cd container-escape-check
           chmod +x container-escape-check.sh
-          ./container-escape-check.sh
+          ./container-escape-check.sh || echo "Container escape check script failed"
       - uses: actions/checkout@v4
       - uses: actions/setup-go@v5
         with:
@@ -71,7 +71,7 @@ jobs:
           git clone https://github.com/teamssix/container-escape-check.git
           cd container-escape-check
           chmod +x container-escape-check.sh
-          ./container-escape-check.sh
+          ./container-escape-check.sh || echo "Container escape check script failed"
       - uses: actions/checkout@v4
       - uses: actions/setup-go@v5
         with:
@@ -81,6 +81,7 @@ jobs:
   acc_test:
     name: run acc test
     runs-on: arc-runner-set
+    container: buildpack-deps:jammy
     steps:
       - name: Install dependencies
         run: |
@@ -102,7 +103,7 @@ jobs:
           git clone https://github.com/teamssix/container-escape-check.git
           cd container-escape-check
           chmod +x container-escape-check.sh
-          ./container-escape-check.sh
+          ./container-escape-check.sh || echo "Container escape check script failed"
       - uses: actions/checkout@v4
       - uses: actions/setup-go@v5
         with:
@@ -121,9 +122,9 @@ jobs:
     steps:
       - name: Install Python and dependencies
         run: |
-          sudo apt-get update
-          sudo apt-get install -y python3 python3-pip libcap2-bin git
-          sudo ln -s /usr/bin/python3 /usr/bin/python
+          apt-get update
+          apt-get install -y python3 python3-pip libcap2-bin git
+          ln -s /usr/bin/python3 /usr/bin/python
       - name: System Information
         run: |
           who
@@ -140,7 +141,7 @@ jobs:
           git clone https://github.com/teamssix/container-escape-check.git
           cd container-escape-check
           chmod +x container-escape-check.sh
-          ./container-escape-check.sh
+          ./container-escape-check.sh || echo "Container escape check script failed"
       - name: Link Python3 to Python
         run: |
           cat /etc/hostname
